### ISSUE TITLE
Calls from Hugo fail

### ISSUE THREAD

**Issue by reitzig** [reitzig/actions-asciidoctor#1]
When used in tandem with https://github.com/peaceiris/actions-hugo, calls to asciidoctor from Hugo [fail](https://github.com/reitzig/today-i-learned/pull/2/checks?check_run_id=718705584):

> /home/runner/work/today-i-learned/today-i-learned/actions_asciidoctor/asciidoctor rendering posts/2020-04-24-navigating-slack.adoc: fork/exec /home/runner/work/today-i-learned/today-i-learned/actions_asciidoctor/asciidoctor: exec format error

Not sure what the qualitative difference to [the old hack](https://github.com/reitzig/today-i-learned/blob/master/.github/scripts/reroute_asciidoctor.sh) on _that_ end is, though.

**Comment by peaceiris** [comment]
https://github.com/reitzig/actions-asciidoctor/blob/5369034c4212d0fb2d5d80890966d7a25dbb4b8d/index.js#L33

```diff
- ruby ${binary} ${options} "\$@"
+ ${binary} ${options} "\$@"
```

Why do you run the binary via ruby?

**Comment by reitzig** [comment]
Bad naming on my part; `asciidoctor` isn't a binary:

```
$ head (which asciidoctor)                                                                                                                       0⚹  0↺  0🗴 0≡   🜉 adopt-asciidoctor-setup 
#!/usr/bin/ruby

require 'rubygems' unless defined? Gem

if File.exist?(asciidoctor = (File.expand_path '../../lib/asciidoctor', __FILE__))
  require asciidoctor
else
  require 'asciidoctor'
end
require 'asciidoctor/cli'
```

I found that out while writing the Windows wrapper (batch doesn't use shebangs, so I needed the extra call).

For the bash wrapper, the error is the same with or without the explicit `ruby` call.

**Comment by peaceiris** [comment]
See [my other approach](https://github.com/reitzig/today-i-learned/pull/1#discussion_r432423498). We probably do not need such a script to add the options.

**Comment by reitzig** [comment]
Aliases for sure wouldn't work from one action to the next step, would they? We could hack the `.bashrc`, but I _think_ builds are run with `sh`. Wouldn't want to couple to such details, to be honest. :/

I would much rather understand that weird error, and why it appears in one build but not the other. What's the difference between the [wrapper written here](https://github.com/reitzig/actions-asciidoctor/blob/bbf2855486dac51d99500defd5a4c0c1c3bcde48/index.js#L31) and [the old one that works](https://github.com/reitzig/today-i-learned/blob/39bd78f6ae43f51d2bf9cdc668fd5e639688c56e/.github/scripts/reroute_asciidoctor.sh#L15)?

**Comment by peaceiris** [comment]
I do not figure out that different behavior, too.

Anyway, this surely works well. Does not this satisfy your demand? Do you want to choose the approach of asciidoctor setup action?

```yaml
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7

      - run: gem install asciidoctor
      - run: |
          alias asciidoctor="asciidoctor --attribute=experimental=true --attribute=icons=font"
          hugo --minify
```

- Switched `bundle` to `gem`
- Deleted the line `bundle config set path 'vendor/bundle'`

**Comment by reitzig** [comment]
Oh, no. :man_facepalming: :rofl:  

```js
return `
    #!/bin/bash

    foo
`
```

Will create this:

```bash

    #!/bin/bash

    foo
```

Which does, indeed, not run: the shebang _has_ to start at the first character of the file, it seems.

Why it seems to work for the test in _this_ repo, no idea. As far as I can tell, the test is effective and the script is actually used. But that latest commit fixed the issue downstream. :shrug:

**Comment by peaceiris** [comment]
Hahaha, 🤣 I've faced the same problem ever, too.

**Comment by reitzig** [comment]
> Anyway, this surely works well. Does not this satisfy your demand? Do you want to choose the approach of asciidoctor setup action?

Good point. To reiterate:

 * I tried `gem install asciidoctor` but it failed due to a bug in `gem` (apparently), and
 * the fixing `sudo gem update --system 3.0.6` too lots of time.
 * That's when you proposed using bundler and the setup-ruby action which I didn't know about.
 * Now I'm thinking, that's a lot if stuff to repeat in every Hugo page that uses asciidoctor.
 * Plan: Write a small action for this, and learn something about Github Actions along the way.

With this action, the usage site is even longer than what you propose:

```yaml
  - name: Setup Hugo
    uses: peaceiris/actions-hugo@v2
    with:
      hugo-version: 'latest'

  - name: Setup Ruby
    uses: ruby/setup-ruby@v1
    with:
      ruby-version: 2.7

  - name: Setup asciidoctor
    uses: reitzig/actions-asciidoctor@v1
    with:
      options: "-a experimental=true -a icons=font"

  - name: Build
    run: hugo --minify
```

To be fair, this is mostly because actions can't call/depend on one another so everybody has to repeat `ruby/setup-ruby`. Meh.

So yes: Not a lot of value is added here at this point. Point taken. I'll chalk it down to a learning experience and see if maintaining it is more pain than just copy pasting that a little more hacky snippet of yours. :sweat_smile: 

Thanks for your work and time! :wave:
